// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8P883kJBWLMfnlxZSSHEOaExIEER60Gs',
    appId: '1:934493095687:web:8896ea9f5a2e6ae438a7a2',
    messagingSenderId: '934493095687',
    projectId: 'universal-yoga-8f236',
    authDomain: 'universal-yoga-8f236.firebaseapp.com',
    databaseURL: 'https://universal-yoga-8f236-default-rtdb.firebaseio.com',
    storageBucket: 'universal-yoga-8f236.firebasestorage.app',
    measurementId: 'G-J34KGF44W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCRcT5PIoQ9cxBJLqHok9L0UOwAKHNNVo',
    appId: '1:934493095687:android:450632508f6c6e9538a7a2',
    messagingSenderId: '934493095687',
    projectId: 'universal-yoga-8f236',
    databaseURL: 'https://universal-yoga-8f236-default-rtdb.firebaseio.com',
    storageBucket: 'universal-yoga-8f236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr0LqV9iiy1X3fj9SDfYkB28nBT8IcCD8',
    appId: '1:934493095687:ios:d5238082ca17243938a7a2',
    messagingSenderId: '934493095687',
    projectId: 'universal-yoga-8f236',
    databaseURL: 'https://universal-yoga-8f236-default-rtdb.firebaseio.com',
    storageBucket: 'universal-yoga-8f236.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr0LqV9iiy1X3fj9SDfYkB28nBT8IcCD8',
    appId: '1:934493095687:ios:d5238082ca17243938a7a2',
    messagingSenderId: '934493095687',
    projectId: 'universal-yoga-8f236',
    databaseURL: 'https://universal-yoga-8f236-default-rtdb.firebaseio.com',
    storageBucket: 'universal-yoga-8f236.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8P883kJBWLMfnlxZSSHEOaExIEER60Gs',
    appId: '1:934493095687:web:5b5d4956ce25661538a7a2',
    messagingSenderId: '934493095687',
    projectId: 'universal-yoga-8f236',
    authDomain: 'universal-yoga-8f236.firebaseapp.com',
    databaseURL: 'https://universal-yoga-8f236-default-rtdb.firebaseio.com',
    storageBucket: 'universal-yoga-8f236.firebasestorage.app',
    measurementId: 'G-984BF8XF71',
  );
}
